CREATE TABLE GAB_5393_INVC_LINE (
ORDER_NO CHAR(7) NOT NULL,
DATE_ORDER DATE NOT NULL,
RECORD_NO CHAR(4) NOT NULL,
LINE_NO CHAR(4) NOT NULL,
INVOICE CHAR(6),
PART CHAR(20),
QTY_SHIPPED NUMERIC(13,4),
PRICE NUMERIC(12,5),
FLAG_BOM CHAR(1),
BOM_PARENT CHAR(4)
);
ALTER TABLE GAB_5393_INVC_LINE 
ADD CONSTRAINT PK_ORDER_NO PRIMARY KEY  (
ORDER_NO,
DATE_ORDER,
RECORD_NO,
LINE_NO )
USING 0;